version: "3"
services:
  app:
    build: .
    command: yarn watch
    volumes:
      - ./:/home/app/
      - /home/app/dist
      - /home/app/node_modules
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
