exports.up = knex => Promise.all([
  knex.schema.createTable('Attachment', table => {
    table.text('Id');
    table.text('AttachmentGroupId');
    table.text('Url');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('AttachmentGroup', table => {
    table.text('Id');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('MemberOfParliament', table => {
    table.text('personId');
    table.text('lastname');
    table.text('firstname');
    table.text('party');
    table.text('minister');
    table.text('XmlData');
    table.text('XmlDataSv');
    table.text('XmlDataFi');
    table.integer('personId_Integer').primary();
  }),
  knex.schema.createTable('SaliDBAanestys', table => {
    table.text('AanestysId');
    table.text('KieliId');
    table.text('IstuntoVPVuosi');
    table.text('IstuntoNumero');
    table.datetime('IstuntoPvm_Datetime');
   table.string('IstuntoPvm');
    table.datetime('IstuntoIlmoitettuAlkuaika_Datetime');
   table.string('IstuntoIlmoitettuAlkuaika');
    table.datetime('IstuntoAlkuaika_Datetime');
   table.string('IstuntoAlkuaika');
    table.text('PJOtsikko');
    table.text('AanestysNumero');
    table.datetime('AanestysAlkuaika_Datetime');
   table.string('AanestysAlkuaika');
    table.datetime('AanestysLoppuaika_Datetime');
   table.string('AanestysLoppuaika');
    table.text('AanestysMitatoity');
    table.text('AanestysOtsikko');
    table.text('AanestysLisaOtsikko');
    table.text('PaaKohtaTunniste');
    table.text('PaaKohtaOtsikko');
    table.text('PaaKohtaHuomautus');
    table.text('KohtaKasittelyOtsikko');
    table.text('KohtaKasittelyVaihe');
    table.text('KohtaJarjestys');
    table.text('KohtaTunniste');
    table.text('KohtaOtsikko');
    table.text('KohtaHuomautus');
    table.text('AanestysTulosJaa');
    table.text('AanestysTulosEi');
    table.text('AanestysTulosTyhjia');
    table.text('AanestysTulosPoissa');
    table.text('AanestysTulosYhteensa');
    table.text('Url');
    table.text('AanestysPoytakirja');
    table.text('AanestysPoytakirjaUrl');
    table.text('AanestysValtiopaivaasia');
    table.text('AanestysValtiopaivaasiaUrl');
    table.text('AliKohtaTunniste');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('AanestysId_Integer').primary();
  }),
  knex.schema.createTable('SaliDBAanestysAsiakirja', table => {
    table.text('AsiakirjaId');
    table.text('AanestysId');
    table.text('Asiakirja');
    table.text('AsiakirjaUrl');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('AsiakirjaId_Integer').primary();
  }),
  knex.schema.createTable('SaliDBAanestysEdustaja', table => {
    table.text('EdustajaId');
    table.text('AanestysId');
    table.text('EdustajaEtunimi');
    table.text('EdustajaSukunimi');
    table.text('EdustajaHenkiloNumero');
    table.text('EdustajaRyhmaLyhenne');
    table.text('EdustajaAanestys');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('EdustajaId_Integer').primary();
  }),
  knex.schema.createTable('SaliDBAanestysJakauma', table => {
    table.text('JakaumaId');
    table.text('AanestysId');
    table.text('Ryhma');
    table.text('Jaa');
    table.text('Ei');
    table.text('Tyhjia');
    table.text('Poissa');
    table.text('Yhteensa');
    table.text('Tyyppi');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('JakaumaId_Integer').primary();
  }),
  knex.schema.createTable('SaliDBAanestysKieli', table => {
    table.text('KieliId');
    table.text('Kieli');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('KieliId_Integer').primary();
  }),
  knex.schema.createTable('SaliDBIstunto', table => {
    table.text('Id');
    table.text('TekninenAvain');
    table.text('IstuntoTyyppi');
    table.text('IstuntoTila');
    table.text('IstuntoTilaSeliteFI');
    table.text('IstuntoTilaSeliteSV');
    table.text('IstuntoVPVuosi');
    table.text('IstuntoNumero');
    table.datetime('IstuntoPvm_Datetime');
   table.string('IstuntoPvm');
    table.datetime('IstuntoIlmoitettuAlkuaika_Datetime');
   table.string('IstuntoIlmoitettuAlkuaika');
    table.datetime('IstuntoAlkuaika_Datetime');
   table.string('IstuntoAlkuaika');
    table.text('IstuntoLoppuaika');
    table.text('IstuntoNimenhuutoaika');
    table.text('KasiteltavaKohtaTekninenAvain');
    table.text('PJTekninenAvain');
    table.text('PJOtsikkoFI');
    table.text('PJOtsikkoSV');
    table.text('PJTila');
    table.text('XmlData');
    table.datetime('Created_Datetime');
   table.string('Created');
    table.datetime('Modified_Datetime');
   table.string('Modified');
    table.text('PuhujaHenkilonumero');
    table.text('ManuaalinenEsto');
    table.text('AttachmentGroupId');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('SaliDBKohta', table => {
    table.text('Id');
    table.text('IstuntoTekninenAvain');
    table.text('TekninenAvain');
    table.text('VaskiID');
    table.text('PuheenvuoroTyyppiOletus');
    table.text('PJKohtaTunnus');
    table.text('Jarjestysnumero');
    table.text('Tunniste');
    table.text('VoikoPyytaaPV');
    table.text('OtsikkoFI');
    table.text('OtsikkoSV');
    table.text('HuomautusFI');
    table.text('HuomautuSV');
    table.text('PaatosFI');
    table.text('PaatosSV');
    table.text('XmlData');
    table.datetime('Created_Datetime');
   table.string('Created');
    table.datetime('Modified_Datetime');
   table.string('Modified');
    table.text('KasittelyotsikkoFI');
    table.text('KasittelyotsikkoSV');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('SaliDBKohtaAanestys', table => {
    table.text('Id');
    table.text('IstuntoTekninenAvain');
    table.text('KohtaTekninenAvain');
    table.text('Aanestysnumero');
    table.datetime('Created_Datetime');
   table.string('Created');
    table.datetime('Modified_Datetime');
   table.string('Modified');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('SaliDBKohtaAsiakirja', table => {
    table.text('Id');
    table.text('KohtaTekninenAvain');
    table.text('TekninenAvain');
    table.text('NimiFI');
    table.text('LinkkiTekstiFI');
    table.text('LinkkiUrlFI');
    table.text('NimiSV');
    table.text('LinkkiTekstiSV');
    table.text('LinkkiUrlSV');
    table.datetime('Created_Datetime');
   table.string('Created');
    table.datetime('Modified_Datetime');
   table.string('Modified');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('SaliDBPuheenvuoro', table => {
    table.text('Id');
    table.text('IstuntoTekninenAvain');
    table.text('KohtaTekninenAvain');
    table.text('TekninenAvain');
    table.datetime('Jarjestys_Datetime');
   table.string('Jarjestys');
    table.text('PVTyyppi');
    table.text('henkilonumero');
    table.text('Etunimi');
    table.text('Sukunimi');
    table.text('Sukupuoli');
    table.text('PyyntoTapa');
    table.datetime('PyyntoAika_Datetime');
   table.string('PyyntoAika');
    table.text('XmlData');
    table.datetime('Created_Datetime');
   table.string('Created');
    table.datetime('Modified_Datetime');
   table.string('Modified');
    table.text('RyhmaLyhenneFI');
    table.text('RyhmaLyhenneSV');
    table.text('Puhunut');
    table.text('JarjestysNro');
    table.text('ADtunnus');
    table.text('MinisteriysFI');
    table.text('MinisteriysSV');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('SaliDBTiedote', table => {
    table.text('Id');
    table.text('TekninenAvain');
    table.text('IstuntoTekninenAvain');
    table.text('KohtaTekninenAvain');
    table.text('TiedoteTyyppi');
    table.text('TiedoteTekstiFI');
    table.text('TiedoteTekstiSV');
    table.text('TiedoteVoimassaolo');
    table.text('TiedoteLahetetty');
    table.datetime('Created_Datetime');
   table.string('Created');
    table.datetime('Modified_Datetime');
   table.string('Modified');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  }),
  knex.schema.createTable('SeatingOfParliament', table => {
    table.text('hetekaId');
    table.text('seatNumber');
    table.text('lastname');
    table.text('firstname');
    table.text('party');
    table.text('minister');
    table.integer('seatNumber_Integer').primary();
  }),
  knex.schema.createTable('VaskiData', table => {
    table.text('Id');
    table.text('XmlData');
    table.text('Status');
    table.datetime('Created_Datetime');
   table.string('Created');
    table.text('Eduskuntatunnus');
    table.text('AttachmentGroupId');
    table.datetime('Imported_Datetime');
   table.string('Imported');
    table.integer('Id_Integer').primary();
  })
]);

exports.down = knex => Promise.all([
  knex.schema.dropTable('Attachment'),
  knex.schema.dropTable('AttachmentGroup'),
  knex.schema.dropTable('MemberOfParliament'),
  knex.schema.dropTable('SaliDBAanestys'),
  knex.schema.dropTable('SaliDBAanestysAsiakirja'),
  knex.schema.dropTable('SaliDBAanestysEdustaja'),
  knex.schema.dropTable('SaliDBAanestysJakauma'),
  knex.schema.dropTable('SaliDBAanestysKieli'),
  knex.schema.dropTable('SaliDBIstunto'),
  knex.schema.dropTable('SaliDBKohta'),
  knex.schema.dropTable('SaliDBKohtaAanestys'),
  knex.schema.dropTable('SaliDBKohtaAsiakirja'),
  knex.schema.dropTable('SaliDBPuheenvuoro'),
  knex.schema.dropTable('SaliDBTiedote'),
  knex.schema.dropTable('SeatingOfParliament'),
  knex.schema.dropTable('VaskiData')
]);
